// Excel Export using SheetJS (xlsx)
// Generates formatted takeoff spreadsheet

import * as XLSX from 'xlsx'

const CATEGORY_ORDER = [
  'Piping',
  'Fittings',
  'Valves',
  'HVAC Equipment',
  'Ductwork',
  'Insulation',
  'Hangers & Supports',
  'Sheet Metal',
  'Other'
]

export function exportToExcel(lineItems, projectName = 'Mechanical Takeoff', summary = '') {
  const wb = XLSX.utils.book_new()

  // ── Sheet 1: Summary Dashboard ──────────────────────────────────────
  const summaryData = [
    ['MECHANICAL & PIPING TAKEOFF REPORT'],
    [''],
    ['Project:', projectName],
    ['Generated:', new Date().toLocaleString()],
    ['Generated By:', 'PipeAI — AI Takeoff Tool'],
    [''],
    ['PROJECT SUMMARY'],
    [summary || 'AI-generated mechanical material takeoff'],
    [''],
    ['CATEGORY SUMMARY'],
    ['Category', 'Item Count', 'Total Quantity', 'Primary Unit'],
  ]

  // Group by category for summary
  const grouped = {}
  lineItems.forEach(item => {
    const cat = item.category || 'Other'
    if (!grouped[cat]) grouped[cat] = []
    grouped[cat].push(item)
  })

  CATEGORY_ORDER.forEach(cat => {
    if (grouped[cat]) {
      const items = grouped[cat]
      const totalQty = items.reduce((sum, i) => sum + (Number(i.quantity) || 0), 0)
      const units = [...new Set(items.map(i => i.unit))].join('/')
      summaryData.push([cat, items.length, totalQty, units])
    }
  })

  summaryData.push([''])
  summaryData.push(['TOTAL ITEMS', lineItems.length, '', ''])

  const summarySheet = XLSX.utils.aoa_to_sheet(summaryData)

  // Style widths
  summarySheet['!cols'] = [
    { wch: 30 }, { wch: 15 }, { wch: 18 }, { wch: 15 }
  ]

  XLSX.utils.book_append_sheet(wb, summarySheet, 'Summary')

  // ── Sheet 2: Full Takeoff ────────────────────────────────────────────
  const takeoffHeaders = [
    'Item #',
    'Category',
    'Description',
    'Size',
    'Material',
    'Unit',
    'Quantity',
    'Notes'
  ]

  const takeoffRows = [takeoffHeaders]
  let rowNum = 1

  CATEGORY_ORDER.forEach(cat => {
    if (!grouped[cat]) return

    // Category header row
    takeoffRows.push([`── ${cat.toUpperCase()} ──`, '', '', '', '', '', '', ''])

    grouped[cat].forEach(item => {
      takeoffRows.push([
        rowNum++,
        item.category || '',
        item.description || '',
        item.size || '',
        item.material || '',
        item.unit || 'EA',
        Number(item.quantity) || 0,
        item.notes || ''
      ])
    })

    takeoffRows.push(['']) // spacer
  })

  const takeoffSheet = XLSX.utils.aoa_to_sheet(takeoffRows)
  takeoffSheet['!cols'] = [
    { wch: 8 },
    { wch: 22 },
    { wch: 45 },
    { wch: 18 },
    { wch: 20 },
    { wch: 8 },
    { wch: 12 },
    { wch: 35 }
  ]

  XLSX.utils.book_append_sheet(wb, takeoffSheet, 'Full Takeoff')

  // ── One sheet per category ───────────────────────────────────────────
  CATEGORY_ORDER.forEach(cat => {
    if (!grouped[cat]) return

    const rows = [
      [cat.toUpperCase() + ' TAKEOFF'],
      [''],
      ['#', 'Description', 'Size', 'Material', 'Unit', 'Quantity', 'Notes']
    ]

    grouped[cat].forEach((item, idx) => {
      rows.push([
        idx + 1,
        item.description || '',
        item.size || '',
        item.material || '',
        item.unit || 'EA',
        Number(item.quantity) || 0,
        item.notes || ''
      ])
    })

    // Total row
    rows.push([''])
    const total = grouped[cat].reduce((sum, i) => sum + (Number(i.quantity) || 0), 0)
    rows.push(['', 'TOTAL', '', '', '', total, ''])

    const sheet = XLSX.utils.aoa_to_sheet(rows)
    sheet['!cols'] = [
      { wch: 6 }, { wch: 45 }, { wch: 18 }, { wch: 20 },
      { wch: 8 }, { wch: 12 }, { wch: 35 }
    ]

    // Shorten tab name to fit Excel's 31-char limit
    const tabName = cat.substring(0, 31)
    XLSX.utils.book_append_sheet(wb, sheet, tabName)
  })

  // ── Export ────────────────────────────────────────────────────────────
  const safeName = projectName.replace(/[^a-zA-Z0-9_\- ]/g, '_').substring(0, 50)
  const date = new Date().toISOString().split('T')[0]
  const fileName = `${safeName}_Takeoff_${date}.xlsx`

  XLSX.writeFile(wb, fileName)
  return fileName
}
